#!/bin/bash


red=$'\e[1;31m'
grn=$'\e[1;32m'
end=$'\e[0m'

success () {
    echo -e "$grn[cased-install] $1$end"
}

fail() {
    echo -e "$red[cased-install] $1$end"

}

# check for python3
if [[ "$(python3 -V)" =~ "Python 3" ]]
then
    PYTHON=python3
    success "Python 3 is installed as python3. Proceeding with installation. This may take a few minutes.."
elif [[ "$(python -V)" =~ "Python 3" ]]
then
    PYTHON=python
    success "Python 3 is installed as python. Proceeding with installation. This may take a few minutes.."
else
    fail "python3 could not be found. Please make sure python3 is installed and on your PATH."
    if [[ "$OSTYPE" == "linux-gnu"* ]]; then
        fail "Please install python3 with your package manager and then try again."
    elif [[ "$OSTYPE" == "darwin"* ]]; then
        fail "You can install python3 easily with homebrew: brew install python3"
    elif [[ "$OSTYPE" == "freebsd"* ]]; then
        fail "Please install python3 with your package manager and then try again."
    else
        fail "Please install python3 with your package manager and then try again."
    fi
    exit 1
fi

if [[ "$($PYTHON -m pip -V)" =~ "python 3" ]]
then
    success "Pip is installed. Proceeding with installation..."
else
    fail "Pip is not installed. Please install with \`curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py && $PYTHON get-pip.py\` or via your package manager."
    exit 1
fi

# check python directories
PACKAGE_PATH=`$PYTHON -c 'import sysconfig; print(sysconfig.get_paths()["purelib"])'`
success "Package path at $PACKAGE_PATH"

if [[ ! -d $PACKAGE_PATH ]]
then
    fail "Python package path ($PACKAGE_PATH) for python3 cannot be found. You may have installation issues."
    fail "If you do encounter issues, try: [sudo] mkdir -p $PACKAGE_PATH"
    fail "If you still have issues, please check https://docs.cased.com/docs/troubleshooting."
fi

set -e

python3 -m pip install cased==0.6.* --upgrade 2> /dev/null || python -m pip install cased==0.6.* --upgrade 1> /dev/null
success "Success: Cased client is installed. Run \`cased configure <your-user-token>\` if this is your first install."
success "Check https://docs.cased.com/docs/getting-started-with-guard for more."
